channels:
- conda-forge
dependencies:
- jupyterlab=0.32.1
- nodejs=8.9
- notebook=5.4
- nbconvert=5.3
- ipykernel=4.7
- ipywidgets=7.2
- widgetsnbextension=3.2
- matplotlib=2.1
- pandas=0.20
- python=3.6
- scikit-image=0.13
- scikit-learn=0.18
- seaborn=0.7
- tensorflow=1.1
- pyyaml
- keras=2.0
